services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME:-ecommerce}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  rabbitmq:
    image: rabbitmq:3.13-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD:-guest}
    ports: ["5672:5672","15672:15672"]
  app:
    build: .
    env_file: .env
    environment:
      DB_HOST: postgres
      RABBIT_HOST: rabbitmq
      REDIS_HOST: redis
    ports: ["8080:8080"]
    depends_on: [postgres, redis, rabbitmq]
